services:
  front-end:
    restart: always
    build:
      context: front-end
      dockerfile: Dockerfile
    volumes:
      - ./front-end:/usr/src/app
    networks:
      - react-express
    ports:
      - "3000:3000"
  back-end:
    restart: always
    build:
      context: back-end
      dockerfile: Dockerfile
    volumes:
      - ./back-end:/usr/src/app
    networks:
      - react-express
    ports:
      - "3001:3001"

networks:
  react-express: